name: Application CI
on:
    push:
        paths:
            - application/**
    pull_request:
        paths:
            - application/**
jobs:
    Application-test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
            - name: Application Test
              working-directory: application
              run: |
                echo "Running tests for the application..."