name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Print OS
          run: uname -a
        - name: Print Current directory
          run: pwd
        - name: List files
          run: ls -la
        - name: Print Git version
          run: git --version
        - name: print Success message
          run: echo "CI workflow completed successfully!"