name: Manual Deploy
on:
    workflow_dispatch:
        inputs:
            environment:
                description: 'Deployment environment'
                required: true
                default: 'dev'
                type: choice
                options:
                    - dev
                    - stg
                    - prod
            version:
                description: 'Version to deploy'
                required: true
                default: '1.0.0'
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Deploy to selected environment
              run: |
                  echo "Deploying version ${{ github.event.inputs.version }}"
                  echo "Deploying to ${{ github.event.inputs.environment }} environment"
        